### ISSUE TITLE
Publish version 2.4

### ISSUE THREAD

**Issue by yaeda** [soenkekluth/browsersync-ssi#8]
Hi! Thanks for this cool module.

Current latest version on npm is 2.3, but this repository has some updates (#4, #5).
Would you update version and publish to npm?

**Comment by soenkekluth** [comment]
done! since this module isn't that much maintained anymore I recommend having a look at: https://github.com/soenkekluth/connect-ssi

**Comment by yaeda** [comment]
Thanks!
